# skillet preamble information used by panhandler
# ---------------------------------------------------------------------
# unique snippet name
name: diab-skillet-simple-soc-conviction-edl-demo
# label used for menu selection
label: diab-skillet-simple-soc-conviction-edl-demo
description: This skillet implements a simple feed to demonstrate SOC convictions in an automated fashion. It uses a flat text file on SE Tools as the feed.

# type of device configuration
# common types are panorama, panos, and template
# https://github.com/PaloAltoNetworks/panhandler/blob/develop/docs/metadata_configuration.rst
type: panos
# preload static or default-based templates
extends:

# grouping of like snippets for dynamic menu creation in panhandler
labels:
  collection:
    - Demo in a Box Collection

# ---------------------------------------------------------------------
# end of preamble section

# variables section
# ---------------------------------------------------------------------
# variables used in the configuration templates
# type_hint defines the form field used by panhandler
# type_hints can be text, ip_address, or dropdown
variables:
  - name: tag_name
    description: Tag Name
    default: EDL
    type_hint: text
  - name: tag_color
    description: Choose Color
    default: Red
    type_hint: dropdown
    dd_list:
      - key: Red
        value: color1
      - key: Blue
        value: color3
      - key: Green
        value: color22
# ---------------------------------------------------------------------
# end of variables section

# snippets section
# ---------------------------------------------------------------------
# snippets used for api configuration including xpath and element as file name
# files will load in the order listed
snippets:
  - name: tag
    xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/tag
    file: tag.xml
  - name: edl_list
    xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/external-list
    file: edl.xml
  - name: edl_list
    xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/rulebase/security/rules
    file: security_rules.xml
# ---------------------------------------------------------------------
# end of snippets section
