# skillet preamble information used by panhandler
# ---------------------------------------------------------------------
# unique snippet name
name: diab-skillet-office365-demo
# label used for menu selection
label: diab-skillet-office365-demo
description: This skillet implements an EDL in Demo in a Box (LiaB) using the Office365 feed on SE Tools through Mine Meld. It is the pre-work setup for the demo.

# type of device configuration
# common types are panorama, panos, and template
# https://github.com/PaloAltoNetworks/panhandler/blob/develop/docs/metadata_configuration.rst
type: panos
# preload static or default-based templates
extends:

# grouping of like snippets for dynamic menu creation in panhandler
labels:
  collection:
    - Demo in a Box Collection

# ---------------------------------------------------------------------
# end of preamble section

# variables section
# ---------------------------------------------------------------------
# variables used in the configuration templates
# type_hint defines the form field used by panhandler
# type_hints can be text, ip_address, or dropdown
variables:
  - name: edl_name
    description: Name of EDL
    default: office365_IPv4
    type_hint: text
  - name: edl_description
    description: Enter a Description
    default: Office365 Mine Meld IPv4 Feed
    type_hint: text
  - name: url
    description: Source url
    type_hint: text
    default: https://192.168.35.132/feeds/o365-any-any-ipv4-feed
  - name: tag_name
    description: Tag Name
    default: EDL
    type_hint: text
  - name: tag_color
    description: Choose Color
    default: Red
    type_hint: dropdown
    dd_list:
      - key: Red
        value: color1
      - key: Blue
        value: color3
      - key: Green
        value: color22
# ---------------------------------------------------------------------
# end of variables section

# snippets section
# ---------------------------------------------------------------------
# snippets used for api configuration including xpath and element as file name
# files will load in the order listed
snippets:
  - name: tag
    xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/tag
    file: tag.xml
  - name: edl_list
    xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/external-list
    file: edl.xml
  - name: edl_list
    xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/rulebase/security/rules
    file: security_rules.xml
# ---------------------------------------------------------------------
# end of snippets section
